version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test123
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  library-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: library
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
